In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv(
    "raw_data/SCMS_Delivery_History_Dataset_20150929.csv",
    encoding="latin1"
)

In [26]:
df.shape

(10324, 33)

In [27]:
print(df.columns.tolist())

['ID', 'Project Code', 'PQ #', 'PO / SO #', 'ASN/DN #', 'Country', 'Managed By', 'Fulfill Via', 'Vendor INCO Term', 'Shipment Mode', 'PQ First Sent to Client Date', 'PO Sent to Vendor Date', 'Scheduled Delivery Date', 'Delivered to Client Date', 'Delivery Recorded Date', 'Product Group', 'Sub Classification', 'Vendor', 'Item Description', 'Molecule/Test Type', 'Brand', 'Dosage', 'Dosage Form', 'Unit of Measure (Per Pack)', 'Line Item Quantity', 'Line Item Value', 'Pack Price', 'Unit Price', 'Manufacturing Site', 'First Line Designation', 'Weight (Kilograms)', 'Freight Cost (USD)', 'Line Item Insurance (USD)']

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10324 entries, 0 to 10323
Data columns (total 34 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   ID                            10324 non-null  int64
 1   Project Code                  10324 non-null  object
 2   PQ #                          10324 non-null  object
 3   PO / SO #                     10324 non-null  object
 4   ASN/DN #                      10324 non-null  object
 5   Country                       10324 non-null  object
 6   Managed By                    10324 non-null  object
 7   Fulfill Via                   10324 non-null  object
 8   Vendor INCO Term              10324 non-null  object
 9   Shipment Mode                 9964 non-null   object
 10  PQ First Sent to Client Date  10324 non-null  object
 11  PO Sent to Vendor Date        10324 non-null  object
 12  Scheduled Delivery Date       10324 non-null  object
 13  Delivered to Client Date      10324 non-null  object
 14  Delivery Recorded Date        10324 non-null  object
 15  Product Group                 10324 non-null  object
 16  Sub Classification            10324 non-null  object
 17  Vendor                        10324 non-null  object
 18  Item Description              10324 non-null  object
 19  Molecule/Test Type            10324 non-null  object
 20  Brand                         10324 non-null  object
 21  Dosage                        8588 non-null   object
 22  Dosage Form                   10324 non-null  object
 23  Unit of Measure (Per Pack)    10324 non-null  int64
 24  Line Item Quantity            10324 non-null  int64
 25  Line Item Value               10324 non-null  float64
 26  Pack Price                    10324 non-null  float64
 27  Unit Price                    10324 non-null  float64
 28  Manufacturing Site            10324 non-null  object
 29  First Line Designation        10324 non-null  object
 30  Weight (Kilograms)            10324 non-null  object
 31  Freight Cost (USD)            10324 non-null  object
 32  Line Item Insurance (USD)     10037 non-null  float64
 33  Freight_Type                  10324 non-null  object
dtypes: float64(4), int64(3), object(27)
memory usage: 2.7+ MB

In [34]:
df.head(5)

,ID,Project Code,PQ #,PO / SO #,ASN/DN #,Country,Managed By,Fulfill Via,Vendor INCO Term,Shipment Mode,...,Unit of Measure (Per Pack),Line Item Quantity,Line Item Value,Pack Price,Unit Price,Manufacturing Site,First Line Designation,Weight (Kilograms),Freight Cost (USD),Line Item Insurance (USD)
0,1,100-CI-T01,Pre-PQ Process,SCMS-4,ASN-8,Côte d'Ivoire,PMO - US,Direct Drop,EXW,Air,...,30,19,551.0,29.00,0.97,Ranbaxy Fine Chemicals LTD,Yes,13,780.34,NaN
1,3,108-VN-T01,Pre-PQ Process,SCMS-13,ASN-85,Vietnam,PMO - US,Direct Drop,EXW,Air,...,240,1000,6200.0,6.20,0.03,"Aurobindo Unit III, India",Yes,358,4521.5,NaN
2,4,100-CI-T01,Pre-PQ Process,SCMS-20,ASN-14,Côte d'Ivoire,PMO - US,Direct Drop,FCA,Air,...,100,500,40000.0,80.00,0.80,ABBVIE GmbH & Co.KG Wiesbaden,Yes,171,1653.78,NaN
3,15,108-VN-T01,Pre-PQ Process,SCMS-78,ASN-50,Vietnam,PMO - US,Direct Drop,EXW,Air,...,60,31920,127360.8,3.99,0.07,"Ranbaxy, Paonta Shahib, India",Yes,1855,16007.06,NaN
4,16,108-VN-T01,Pre-PQ Process,SCMS-81,ASN-55,Vietnam,PMO - US,Direct Drop,EXW,Air,...,60,38000,121600.0,3.20,0.05,"Aurobindo Unit III, India",Yes,7590,45450.08,NaN

In [6]:
df.isnull().sum()

ID                                 0
Project Code                       0
PQ #                               0
PO / SO #                          0
ASN/DN #                           0
Country                            0
Managed By                         0
Fulfill Via                        0
Vendor INCO Term                   0
Shipment Mode                    360
PQ First Sent to Client Date       0
PO Sent to Vendor Date             0
Scheduled Delivery Date            0
Delivered to Client Date           0
Delivery Recorded Date             0
Product Group                      0
Sub Classification                 0
Vendor                             0
Item Description                   0
Molecule/Test Type                 0
Brand                              0
Dosage                          1736
Dosage Form                        0
Unit of Measure (Per Pack)         0
Line Item Quantity                 0
Line Item Value                    0
Pack Price                         0
Unit Price                         0
Manufacturing Site                 0
First Line Designation             0
Weight (Kilograms)                 0
Freight Cost (USD)                 0
Line Item Insurance (USD)        287
dtype: int64

In [8]:
#chacking total null values in entire dataframe
df.isnull().sum().sum()

np.int64(2383)

In [10]:
#columns with null percentage greater then 0% 
null_percentage = (df.isnull().sum()/len(df) *100)
null_percentage = null_percentage[null_percentage > 0]
print(null_percentage)

Shipment Mode                 3.487021
Dosage                       16.815188
Line Item Insurance (USD)     2.779930
dtype: float64

In [11]:
#Only columns with null values

df.isnull().sum()[df.isnull().sum() >0]

Shipment Mode                 360
Dosage                       1736
Line Item Insurance (USD)     287
dtype: int64

In [18]:
#first 5 values of Freight Cost (USD) column
df["Freight Cost (USD)"]

0                                    780.34
1                                    4521.5
2                                   1653.78
3                                  16007.06
4                                  45450.08
                        ...
10319               See DN-4307 (ID#:83920)
10320               See DN-4313 (ID#:83921)
10321    Freight Included in Commodity Cost
10322    Freight Included in Commodity Cost
10323    Freight Included in Commodity Cost
Name: Freight Cost (USD), Length: 10324, dtype: object

In [22]:
# first 5 values of weight(kilograms) 
df["Weight (Kilograms)"]

0                                13
1                               358
2                               171
3                              1855
4                              7590
                    ...
10319       See DN-4307 (ID#:83920)
10320       See DN-4313 (ID#:83921)
10321    Weight Captured Separately
10322                          1392
10323    Weight Captured Separately
Name: Weight (Kilograms), Length: 10324, dtype: object

In [39]:
#percentage of Freight Included in Commodity Cost string in freight cost column
(df["Freight Cost (USD)"] == "Freight Included in Commodity Cost").sum()/len(df) * 100

np.float64(13.967454475009685)

In [41]:
#percentage of Freight Included in Commodity Cost string in freight cost column using mean 
(df["Freight Cost (USD)"] == "Freight Included in Commodity Cost") .mean() * 100

np.float64(13.967454475009685)

In [26]:
# unique values in shipment mode column
df["Shipment Mode"].unique()

array(['Air', nan, 'Truck', 'Air Charter', 'Ocean'], dtype=object)

In [28]:
# percentage of null values in each column 
(df.isnull().sum()/len(df))*100

ID                               0.000000
Project Code                     0.000000
PQ #                             0.000000
PO / SO #                        0.000000
ASN/DN #                         0.000000
Country                          0.000000
Managed By                       0.000000
Fulfill Via                      0.000000
Vendor INCO Term                 0.000000
Shipment Mode                    3.487021
PQ First Sent to Client Date     0.000000
PO Sent to Vendor Date           0.000000
Scheduled Delivery Date          0.000000
Delivered to Client Date         0.000000
Delivery Recorded Date           0.000000
Product Group                    0.000000
Sub Classification               0.000000
Vendor                           0.000000
Item Description                 0.000000
Molecule/Test Type               0.000000
Brand                            0.000000
Dosage                          16.815188
Dosage Form                      0.000000
Unit of Measure (Per Pack)       0.000000
Line Item Quantity               0.000000
Line Item Value                  0.000000
Pack Price                       0.000000
Unit Price                       0.000000
Manufacturing Site               0.000000
First Line Designation           0.000000
Weight (Kilograms)               0.000000
Freight Cost (USD)               0.000000
Line Item Insurance (USD)        2.779930
dtype: float64

In [47]:
# counting rows where freight cost contains non numeric values

(df["Freight Cost (USD)"].astype(str).str.contains(r"[A-Za-z]", na = False). sum())

np.int64(4126)

In [3]:
# Creating a new column called Freight_Type


df["Freight_Type"] = np.where(df["Freight Cost (USD)"].str.contains(r"[A-Za-z]",na = False), "Absorbed" ,"Separate")

In [8]:
#  inspecting last 10 values of both the columns "Freight_Type","Freight Cost (USD)"

df[["Freight_Type","Freight Cost (USD)"]].tail(10)

      Freight_Type                  Freight Cost (USD)
10314     Absorbed             See DN-4274 (ID#:84472)
10315     Separate                               26180
10316     Separate                                3410
10317     Absorbed             See DN-4282 (ID#:83919)
10318     Absorbed             See DN-4307 (ID#:83920)
10319     Absorbed             See DN-4307 (ID#:83920)
10320     Absorbed             See DN-4313 (ID#:83921)
10321     Absorbed  Freight Included in Commodity Cost
10322     Absorbed  Freight Included in Commodity Cost
10323     Absorbed  Freight Included in Commodity Cost

In [10]:
#Printing value counts of freight_type column using (.value_count() funtion)

df["Freight_Type"].value_counts()

Freight_Type
Separate    6198
Absorbed    4126
Name: count, dtype: int64

In [12]:
df[
    pd.to_numeric(df["Freight Cost (USD)"], errors="coerce").isna()
]

,ID,Project Code,PQ #,PO / SO #,ASN/DN #,Country,Managed By,Fulfill Via,Vendor INCO Term,Shipment Mode,...,Line Item Quantity,Line Item Value,Pack Price,Unit Price,Manufacturing Site,First Line Designation,Weight (Kilograms),Freight Cost (USD),Line Item Insurance (USD),Freight_Type
6,44,110-ZM-T01,Pre-PQ Process,SCMS-139,ASN-130,Zambia,PMO - US,Direct Drop,DDU,Air,...,135,4374.00,32.40,0.36,MSD South Granville Australia,Yes,328,Freight Included in Commodity Cost,NaN,Absorbed
8,46,112-NG-T01,Pre-PQ Process,SCMS-156,ASN-93,Nigeria,PMO - US,Direct Drop,EXW,Air,...,273,532.35,1.95,0.03,"Aurobindo Unit III, India",No,See ASN-93 (ID#:1281),See ASN-93 (ID#:1281),NaN,Absorbed
9,47,110-ZM-T01,Pre-PQ Process,SCMS-165,ASN-199,Zambia,PMO - US,Direct Drop,CIP,Air,...,2800,115080.00,41.10,0.34,ABBVIE (Abbott) St. P'burg USA,Yes,643,Freight Included in Commodity Cost,NaN,Absorbed
10,60,110-ZM-T01,Pre-PQ Process,SCMS-221,ASN-223,Zambia,PMO - US,Direct Drop,CIP,Air,...,2800,115080.00,41.10,0.34,ABBVIE Ludwigshafen Germany,Yes,643,Freight Included in Commodity Cost,NaN,Absorbed
12,62,102-NG-T01,Pre-PQ Process,SCMS-230,ASN-144,Nigeria,PMO - US,Direct Drop,EXW,Air,...,10,850.00,85.00,0.85,"EY Laboratories, USA",Yes,Weight Captured Separately,Invoiced Separately,NaN,Absorbed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10319,86818,103-ZW-T30,FPQ-15197,SO-50020,DN-4307,Zimbabwe,PMO - US,From RDC,N/A - From RDC,Truck,...,166571,599655.60,3.60,0.06,"Mylan, H-12 & H-13, India",No,See DN-4307 (ID#:83920),See DN-4307 (ID#:83920),705.79,Absorbed
10320,86819,104-CI-T30,FPQ-15259,SO-50102,DN-4313,Côte d'Ivoire,PMO - US,From RDC,N/A - From RDC,Truck,...,21072,137389.44,6.52,0.11,Hetero Unit III Hyderabad IN,No,See DN-4313 (ID#:83921),See DN-4313 (ID#:83921),161.71,Absorbed
10321,86821,110-ZM-T30,FPQ-14784,SO-49600,DN-4316,Zambia,PMO - US,From RDC,N/A - From RDC,Truck,...,514526,5140114.74,9.99,0.33,Cipla Ltd A-42 MIDC Mahar. IN,No,Weight Captured Separately,Freight Included in Commodity Cost,5284.04,Absorbed
10322,86822,200-ZW-T30,FPQ-16523,SO-51680,DN-4334,Zimbabwe,PMO - US,From RDC,N/A - From RDC,Truck,...,17465,113871.80,6.52,0.11,Mylan (formerly Matrix) Nashik,Yes,1392,Freight Included in Commodity Cost,134.03,Absorbed
10323,86823,103-ZW-T30,FPQ-15197,SO-50022,DN-4336,Zimbabwe,PMO - US,From RDC,N/A - From RDC,Truck,...,36639,72911.61,1.99,0.03,"Cipla, Goa, India",No,Weight Captured Separately,Freight Included in Commodity Cost,85.82,Absorbed

In [14]:
df["Freight Cost (USD)"] = pd.to_numeric(df["Freight Cost (USD)"], errors ="coerce")

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10324 entries, 0 to 10323
Data columns (total 34 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   ID                            10324 non-null  int64
 1   Project Code                  10324 non-null  object
 2   PQ #                          10324 non-null  object
 3   PO / SO #                     10324 non-null  object
 4   ASN/DN #                      10324 non-null  object
 5   Country                       10324 non-null  object
 6   Managed By                    10324 non-null  object
 7   Fulfill Via                   10324 non-null  object
 8   Vendor INCO Term              10324 non-null  object
 9   Shipment Mode                 9964 non-null   object
 10  PQ First Sent to Client Date  10324 non-null  object
 11  PO Sent to Vendor Date        10324 non-null  object
 12  Scheduled Delivery Date       10324 non-null  object
 13  Delivered to Client Date      10324 non-null  object
 14  Delivery Recorded Date        10324 non-null  object
 15  Product Group                 10324 non-null  object
 16  Sub Classification            10324 non-null  object
 17  Vendor                        10324 non-null  object
 18  Item Description              10324 non-null  object
 19  Molecule/Test Type            10324 non-null  object
 20  Brand                         10324 non-null  object
 21  Dosage                        8588 non-null   object
 22  Dosage Form                   10324 non-null  object
 23  Unit of Measure (Per Pack)    10324 non-null  int64
 24  Line Item Quantity            10324 non-null  int64
 25  Line Item Value               10324 non-null  float64
 26  Pack Price                    10324 non-null  float64
 27  Unit Price                    10324 non-null  float64
 28  Manufacturing Site            10324 non-null  object
 29  First Line Designation        10324 non-null  object
 30  Weight (Kilograms)            10324 non-null  object
 31  Freight Cost (USD)            6198 non-null   float64
 32  Line Item Insurance (USD)     10037 non-null  float64
 33  Freight_Type                  10324 non-null  object
dtypes: float64(5), int64(3), object(26)
memory usage: 2.7+ MB